markdown: kramdown
title: ddigiorg.github.io
url: https://ddigiorg.github.io/
exclude: ["README.md"]

# Setup a pages collection (see `./_pages/')
collections:
  pages:
    output: true
    permalink: /:path/